### ISSUE TITLE
Error: <circle> attribute r: Expected length, "NaN".

### ISSUE THREAD

**Issue by lukehorvat** [hughsk/tap-to-start#1]
Hi, I'm looking at the demo at http://hughsk.io/tap-to-start.

I'm seeing the following error logged to the console several times in Google Chrome:

```
Error: <circle> attribute r: Expected length, "NaN".
```

Being thrown from [this line](https://github.com/hughsk/tap-to-start/blob/3a5c6d4/index.js#L88).

Any idea what it is?

**Comment by hughsk** [comment]
Ah, sometimes `NaN` was turning up in the transition variables (`ts`, `tp`, `tt`) because a variable wasn't initiated — fixed! Thanks for the report :)

**Comment by lukehorvat** [comment]
Thank you. Nice work!
